TASK [Generate AppArmor profile for Nginx] *************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["aa-autodep", "nginx"], "delta": "0:00:01.258956", "end": "2024-05-05 13:21:00.419157", "msg": "non-zero return code", "rc": 1, "start": "2024-05-05 13:20:59.160201", "stderr": "Traceback (most recent call last):\n  File \"/usr/sbin/aa-autodep\", line 34, in <module>\n    tool.cmd_autodep()\n  File \"/usr/lib/python3/dist-packages/apparmor/tools.py\", line 173, in cmd_autodep\n    aaui.UI_Info(_('Profile for %s already exists - skipping.') % program)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'str' object is not callable\n\n\nAn unexpected error occurred!\n\nFor details, see /tmp/apparmor-bugreport-6ie7mweo.txt\nPlease consider reporting a bug at https://gitlab.com/apparmor/apparmor/-/issues\nand attach this file.", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/sbin/aa-autodep\", line 34, in <module>", "    tool.cmd_autodep()", "  File \"/usr/lib/python3/dist-packages/apparmor/tools.py\", line 173, in cmd_autodep", "    aaui.UI_Info(_('Profile for %s already exists - skipping.') % program)", "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "TypeError: 'str' object is not callable", "", "", "An unexpected error occurred!", "", "For details, see /tmp/apparmor-bugreport-6ie7mweo.txt", "Please consider reporting a bug at https://gitlab.com/apparmor/apparmor/-/issues", "and attach this file."], "stdout": "", "stdout_lines": []}

